DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100),
NUMERO VARCHAR(20),
LOCALIDAD VARCHAR(20),
PROVINCIA VARCHAR(20));
DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100),
NOMBRE VARCHAR(100),
DOCUMENTO VARCHAR(100),
FECHA_INGRESO DATE,
DOMICILIO_ID INT,
EMAIL VARCHAR(100));